# Generated by Django 5.1.3 on 2024-11-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='coupon_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
