# Generated by Django 5.1.3 on 2024-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=12234, max_length=20),
            preserve_default=False,
        ),
    ]
