# Generated by Django 5.1.3 on 2024-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_rating',
            field=models.IntegerField(choices=[('', 'How many stars would you give this product?'), (1, '★ (Poor)'), (2, '★★ (Fair)'), (3, '★★★ (Average)'), (4, '★★★★ (Good)'), (5, '★★★★★ (Great)')], default=None),
        ),
    ]
